### ISSUE TITLE
Regex not working on newer file starting with 'GX'

### ISSUE THREAD

**Issue by fefetost** [sebnil/gopro_joiner#1]
Older file starts with GP or GH newer gopro's file starts with GX
![Immagine 2021-11-19 102118](https://user-images.githubusercontent.com/46992292/142598104-f2493683-84fe-4c25-a795-e9da2f316332.png)

**Comment by sebnil** [comment]
Closed by https://github.com/sebnil/gopro_joiner/pull/2#event-5682913252
Thanks @fefetost !
